### PR TITLE
Sponsors page mods

### PR DESCRIPTION
**Pull request by CraigSnowden**
It's me again... you might want to express one of the commits differently, up to you. Also if you'd rather I pissed off, that's fine too :-)

### CODE REVIEW

**Comment by issyl0** [comment]
Oh.  The PeopleFund.it part of this is what I just asked for Adam to pull in too.  I was puzzled by the apostrophes.  I should have looked here beforehand!  :-)

**Comment by CraigSnowden** [comment]
I probably should have been more explicit :D

CSn

**Comment by adamamyl** [comment]
> What on earth is a schrapnel separator?!

The decimal mark/radix point:

four-pounds-twenty-five-pence might be expressed: £4,25 (all change is schrapnel, in the Book of Adam) -- see http://en.wikipedia.org/wiki/Decimal_mark.

Note, we rarely use pence, using round numbers (and without  a terminating ",00", 20k is 20'000, not 20'000,00 (style-guide) nor 20,000.00)

**Comment by CraigSnowden** [comment]
Comma, not a point for splitting the fraction? This is all new to me... 

What about spaces as a thousand separator, SI style?

It's your style but I'm bored enough to question it

**Pull request closed without merging**
